version: '3'
services:
  node:
    build: .
    container_name: app-node
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  mariadb:
    image: mariadb:10.4.5
    container_name: app-mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=app
    volumes:
      - ./mariadb-conf.d:/etc/mysql/conf.d
